### ISSUE TITLE
Support private encoding option from draft-ietf-netconf-udp-notif-03

### ISSUE THREAD

**Issue by pierre-francois** [insa-unyte/udp-notif-c-collector#72]
Support of the private encoding option described in draft-ietf-netconf-udp-notif-03
Use temporary type: 2
- [x] Update parser
- [x] Update metadata struct to provide the option value to the lib user

**Comment by ahuangfeng** [comment]
Private encoding and custom options are implemented and merged on `development` branch.
Will be released in v0.5.2.
