### ISSUE TITLE
Tag 0.4.1

### ISSUE THREAD

**Issue by paololucente** [insa-unyte/udp-notif-c-collector#76]
Dearest Superstars,

Any chance you can real quick issue a tag 0.4.1 for commit 1e72b5fa436b2ac1e561b216bf800267eab273a8 (right before you bump to 0.5.0 and make relevant API changes)? I'd love to point pmacct CI to such tag.

Paolo

**Comment by ahuangfeng** [comment]
I just created tag `v0.4.1` on commit `1e72b5f`. Can you test from your side ? This commit already have major changes on the api.

**Comment by paololucente** [comment]
Thank you Alex ( @ahuangfeng ), it worked perfect. Paolo
